language: ruby
rvm:
  - 2.3.3
sudo: false
cache: bundler
only: master
env:
  matrix:
    - SOLIDUS_BRANCH=v1.0 DB=mysql
    - SOLIDUS_BRANCH=v1.0 DB=postgresql
    - SOLIDUS_BRANCH=v1.1 DB=mysql
    - SOLIDUS_BRANCH=v1.1 DB=postgresql
    - SOLIDUS_BRANCH=v1.2 DB=mysql
    - SOLIDUS_BRANCH=v1.2 DB=postgresql
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=postgresql
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=postgresql
    - SOLIDUS_BRANCH=v2.0 DB=mysql
    - SOLIDUS_BRANCH=v2.0 DB=postgresql
    - SOLIDUS_BRANCH=v2.1 DB=mysql
    - SOLIDUS_BRANCH=v2.1 DB=postgresql
    - SOLIDUS_BRANCH=master DB=mysql
    - SOLIDUS_BRANCH=master DB=postgresql
before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
  - bundler --version
